### ISSUE TITLE
Has Something Changed? Title Bar is still Visible

### ISSUE THREAD

**Issue by jimgilliam** [captainbrosset/1DIV#1]
Is there something different that's happened in Edge? This does not hide the title bar or edit it. When I build the bar is still there just as in a default app.

Can we not customize it anymore?

**Comment by captainbrosset** [comment]
Still working fine for me. Here are a couple of screenshots from the app installed on Windows 11, with the Window Controls Overlay feature enabled:

![image](https://github.com/captainbrosset/1DIV/assets/1152698/2084a3c2-be6c-44a0-8c00-1d370c6b9be9)

![image](https://github.com/captainbrosset/1DIV/assets/1152698/d1ebd808-c779-4521-9c5b-26277d3b096c)

Note that, by default, the feature is **not** enabled for users. As a user, you first need to click on the chevron icon (**Hide title bar**) to enable the feature:

![image](https://github.com/captainbrosset/1DIV/assets/1152698/fa7d0c84-6f2a-425e-90bd-6897e0b3b934)

**Comment by jimgilliam** [comment]
Apologies for the multiple posts. @captainbrosset Captain, it's working now after adjustments to my manifest. Thank you.
